# Simulation script for LED_AXI_GPIO_MB with real .elf preloaded into LMB BRAM.
# Usage: vivado -mode batch -source sim.tcl
set script_dir [file dirname [info script]]
cd $script_dir

open_project ./LED_AXI_GPIO_MB.xpr

# Add testbench to sim fileset
set tb ./tb_design_1.v
if {[lsearch [get_files -of [get_filesets sim_1]] $tb] == -1} {
    add_files -fileset sim_1 -norecurse $tb
}
set_property top tb_design_1 [get_filesets sim_1]

# Preload ELF into LMB BRAM: mem file generated by updatemem from the ELF.
set MEMFILE /tmp/memfiles/design_1_lmb_bram_0.mem
set bramcell [get_cells -hier -filter {NAME =~ *lmb_bram*}]
puts "BRAM cell: $bramcell"
set_property -name {MEM_FILE} -value $MEMFILE -objects [get_cells -hier -filter {NAME =~ *lmb_bram*}]
set_property -name {xsim.simulate.runtime} -value {2ms} -objects [get_filesets sim_1]
set_property -name {xsim.simulate.log_all_signals} -value {true} -objects [get_filesets sim_1]

launch_simulation

puts "=== SIM DONE ==="
puts "WDB: [file normalize xsim/tb_design_1/tb_design_1.wdb]"