// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="moving_max_moving_max,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.572000,HLS_SYN_LAT=2058,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=111,HLS_SYN_LUT=322,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module moving_max (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_data_address0,
        in_data_ce0,
        in_data_q0,
        out_data_address0,
        out_data_ce0,
        out_data_we0,
        out_data_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] in_data_address0;
output   in_data_ce0;
input  [31:0] in_data_q0;
output  [5:0] out_data_address0;
output   out_data_ce0;
output   out_data_we0;
output  [31:0] out_data_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [6:0] add_ln19_fu_221_p2;
reg   [6:0] add_ln19_reg_313;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln19_fu_227_p1;
reg   [63:0] zext_ln19_reg_318;
wire   [2:0] add_ln25_fu_237_p2;
reg   [2:0] add_ln25_reg_327;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [3:0] add_ln32_fu_264_p2;
reg   [3:0] add_ln32_reg_355;
wire   [31:0] m_2_fu_280_p3;
wire    ap_CS_fsm_state8;
wire   [31:0] window_q0;
reg   [2:0] k_1_reg_143;
wire   [0:0] icmp_ln19_fu_215_p2;
wire    ap_CS_fsm_state5;
reg   [3:0] k_2_reg_155;
reg   [31:0] m_1_reg_166;
wire   [63:0] zext_ln14_fu_197_p1;
wire   [0:0] icmp_ln14_fu_185_p2;
wire   [63:0] zext_ln25_fu_243_p1;
wire   [0:0] icmp_ln24_fu_231_p2;
wire   [63:0] zext_ln24_fu_248_p1;
wire   [63:0] zext_ln32_fu_259_p1;
wire   [0:0] icmp_ln32_fu_253_p2;
reg   [3:0] k_fu_62;
wire   [3:0] add_ln14_fu_191_p2;
reg   [6:0] n_fu_70;
reg    window_we0_local;
reg   [31:0] window_d0_local;
reg    window_ce0_local;
reg   [2:0] window_address0_local;
reg    in_data_ce0_local;
reg    out_data_we0_local;
reg    out_data_ce0_local;
wire   [0:0] icmp_ln33_fu_274_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 k_fu_62 = 4'd0;
#0 n_fu_70 = 7'd0;
end

moving_max_window_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0_local),
    .ce0(window_ce0_local),
    .we0(window_we0_local),
    .d0(window_d0_local),
    .q0(window_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        k_1_reg_143 <= add_ln25_reg_327;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_215_p2 == 1'd0))) begin
        k_1_reg_143 <= 3'd7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        k_2_reg_155 <= add_ln32_reg_355;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        k_2_reg_155 <= 4'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_fu_62 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln14_fu_185_p2 == 1'd0))) begin
        k_fu_62 <= add_ln14_fu_191_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        m_1_reg_166 <= m_2_fu_280_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        m_1_reg_166 <= in_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln14_fu_185_p2 == 1'd1))) begin
        n_fu_70 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln32_fu_253_p2 == 1'd1))) begin
        n_fu_70 <= add_ln19_reg_313;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln19_reg_313 <= add_ln19_fu_221_p2;
        zext_ln19_reg_318[6 : 0] <= zext_ln19_fu_227_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln25_reg_327 <= add_ln25_fu_237_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln32_reg_355 <= add_ln32_fu_264_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_215_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_215_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_data_ce0_local = 1'b1;
    end else begin
        in_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_data_ce0_local = 1'b1;
    end else begin
        out_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln32_fu_253_p2 == 1'd1))) begin
        out_data_we0_local = 1'b1;
    end else begin
        out_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        window_address0_local = zext_ln32_fu_259_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        window_address0_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        window_address0_local = zext_ln24_fu_248_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        window_address0_local = zext_ln25_fu_243_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        window_address0_local = zext_ln14_fu_197_p1;
    end else begin
        window_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5))) begin
        window_ce0_local = 1'b1;
    end else begin
        window_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        window_d0_local = in_data_q0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        window_d0_local = window_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        window_d0_local = 32'd2147483648;
    end else begin
        window_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln14_fu_185_p2 == 1'd0)))) begin
        window_we0_local = 1'b1;
    end else begin
        window_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln14_fu_185_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_215_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln24_fu_231_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln32_fu_253_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln14_fu_191_p2 = (k_fu_62 + 4'd1);

assign add_ln19_fu_221_p2 = (n_fu_70 + 7'd1);

assign add_ln25_fu_237_p2 = ($signed(k_1_reg_143) + $signed(3'd7));

assign add_ln32_fu_264_p2 = (k_2_reg_155 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign icmp_ln14_fu_185_p2 = ((k_fu_62 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_215_p2 = ((n_fu_70 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_231_p2 = ((k_1_reg_143 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_253_p2 = ((k_2_reg_155 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_274_p2 = (($signed(window_q0) > $signed(m_1_reg_166)) ? 1'b1 : 1'b0);

assign in_data_address0 = zext_ln19_reg_318;

assign in_data_ce0 = in_data_ce0_local;

assign m_2_fu_280_p3 = ((icmp_ln33_fu_274_p2[0:0] == 1'b1) ? window_q0 : m_1_reg_166);

assign out_data_address0 = zext_ln19_reg_318;

assign out_data_ce0 = out_data_ce0_local;

assign out_data_d0 = m_1_reg_166;

assign out_data_we0 = out_data_we0_local;

assign zext_ln14_fu_197_p1 = k_fu_62;

assign zext_ln19_fu_227_p1 = n_fu_70;

assign zext_ln24_fu_248_p1 = k_1_reg_143;

assign zext_ln25_fu_243_p1 = add_ln25_fu_237_p2;

assign zext_ln32_fu_259_p1 = k_2_reg_155;

always @ (posedge ap_clk) begin
    zext_ln19_reg_318[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //moving_max
